### ISSUE TITLE
No handler for 'ping' or 'pong' message

### ISSUE THREAD

**Issue by leonkaihao** [theturtle32/WebSocket-Node#208] opened 2015-07-23 05:28 UTC
It seems that there is no message event for user to handle ping-pong.
In some scenarios I have to print pong messages into log file, to confirm the network is OK.

**Comment by leonkaihao** [comment] 2015-07-23 05:31
May be I can handle 'frame' events, and unpack it by myself, but seems not convenient

**Comment by theturtle32** [comment] 2015-07-28 06:42
Closing as duplicate of #205

**Closed by theturtle32** 2015-07-28 06:42 UTC
